### PR TITLE
fix(add_sa_role): Switch $EXPIRY to use python3 instead of date

### LINKED ISSUE #2: Linux/Mac Compatibility issue in add_sa_role.sh
When calling the `date` function at https://github.com/eq-stacks/template-repo/blob/main/scripts/add_sa_role.sh#L6, Linux and Mac will provide different outputs. It works fine on Linux, but when running from a mac it creates a role with an invalid Expiry, which GCP rightly treats as no role at all

### PR DESCRIPTION
**Pull request by rodriguezcondec**
**Issue summary:**

When calling the date function at https://github.com/eq-stacks/template-repo/blob/main/scripts/add_sa_role.sh#L6, Linux and Mac will provide different outputs. It works fine on Linux, but when running from a mac it creates a role with an invalid Expiry, which GCP rightly treats as no role at all

**Proposed solution:**

In order to avoid Linux/MacOS compatibility issues, we use python which behaves the same regardless of the environment. This solution seems to be better than just creating a symlink or filling the scripts with conditionals to check the `$OSTYPE` variable.

### CODE REVIEW

File: scripts/add_sa_role.sh [hunk 1]
```diff
@@ -1,16 +1,13 @@
...
-EXPIRY=$(printf '%(%Y-%m-%dT%H:%M:%SZ)T' $TIMESTAMP_PLUS_EXPIRY)
+EXPIRY=$(python3 -c 'from datetime import datetime, timedelta; now = datetime.utcnow(); expires = now + timedelta(hours=1); print(expires.strftime("%Y-%m-%dT%H:%M:%SZ"))')
 SA_PROJECT=$(gcloud config get-value project)
 SERVICE_ACCOUNT="terraform@$SA_PROJECT.iam.gserviceaccount.com"
 
 gcloud organizations add-iam-policy-binding "$ORG_ID" \
   --member="serviceAccount:$SERVICE_ACCOUNT" \
   --role "organizations/$ORG_ID/roles/terraformServiceAccount" \
-  --condition="expression=request.time < timestamp('$EXPIRY'),title=Expiry: $EXPIRY"
+  --condition="expression=request.time < timestamp('$EXPIRY'),title=Expiry: $EXPIRY"
```
Comment (aphelionz) [inline scripts/add_sa_role.sh]: Please fix the newline issue - you should be able to configure your text editor to automatically add a newline at the end of files 👍

**Review by aphelionz — CHANGES_REQUESTED** [review]
Tested and working on Mac 🎉 Just one minor change re: the newline

File: scripts/add_sa_role.sh (hunk 1 above)
Comment (rodriguezcondec) [reply scripts/add_sa_role.sh]: Done!

**Review by aphelionz — APPROVED** [review]
